---
# handlers/main.yml (rsyncd)
# Prefix : rsyncd

- name: Restart rsyncd
  systemd:
    name: rsync.service
    state: restarted

- name: "Print warning for rsyncd (Check for deleted variables)"
  debug:
    msg: "{{ __rsyncd_check_deleted_vars.stdout_lines }}"
  failed_when: yes
  ignore_errors: yes
